#!/usr/bin/env python
"""The tuned fine-tune against both baselines, like for like (§6.2).

§6.2's comparison table pitted the *tuned* fine-tune against the *untuned*
fingerprint baseline. That basis was never stated, and it is not neutral:

  n = 50    untuned B1 (0.704) is STRONGER than tuned B1 (0.714), so the
            undisclosed basis made T2's task harder -- conservative.
  n = 347   tuned B1 (0.601) is STRONGER than untuned B1 (0.634), so the same
            basis made T2's task easier -- generous, in a section whose whole
            subject is equal search budgets.

The conclusion survives either way, and is in fact firmer under the like-for-like
comparison, but a reader cannot check that unless both are reported. This script
computes both.

Writes results/tables/table13_tuned_comparison.csv
"""
from __future__ import annotations

import glob
import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

OUT = Path("results/tables/table13_tuned_comparison.csv")
ARM_T2 = "T2_chemberta_full_finetune"
ARM_B1 = "B1_ecfp_histgb"


def load(directory: str, arm: str, n: int, split: str = "scaffold") -> dict:
    out = {}
    for f in glob.glob(f"{directory}/{arm}__{split}__seed*__n{n}.json"):
        d = json.load(open(f))
        out[d["seed"]] = d["metrics"]
    return out


def compare(a: dict, b: dict, metric: str = "rmse") -> dict | None:
    seeds = sorted(set(a) & set(b))
    if len(seeds) < 3:
        return None
    x = np.array([a[s][metric] for s in seeds])
    y = np.array([b[s][metric] for s in seeds])
    return {"n_seeds": len(seeds),
            "tuned_T2_median": round(float(np.median(x)), 4),
            "baseline_median": round(float(np.median(y)), 4),
            "T2_better_in_seeds": int((x < y).sum()),
            "p_raw": round(float(stats.wilcoxon(x, y).pvalue), 4)}


def main() -> int:
    rows = []
    for n in (50, 347):
        t2 = load("results/tuned_metrics", ARM_T2, n)
        for basis, b in (("untuned B1 (the basis §6.2 originally used)",
                          load("results/metrics", ARM_B1, n)),
                         ("tuned B1 (like for like)",
                          load("results/tuned_metrics", ARM_B1, n))):
            r = compare(t2, b)
            if r:
                rows.append({"n_train": n, "baseline_basis": basis, **r,
                             "verdict": "T2 better" if r["p_raw"] <= 0.05 and
                                        r["tuned_T2_median"] < r["baseline_median"]
                                        else "baseline better" if r["p_raw"] <= 0.05
                                        else "inconclusive"})
    df = pd.DataFrame(rows)
    OUT.write_text(
        f"# generated by scripts/analyse_tuning.py on "
        f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}\n"
        f"# tuned fine-tune vs both bases; paired Wilcoxon over matched seeds\n"
        + df.to_csv(index=False))
    print(f"wrote {OUT}")
    print(df.to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
