#!/usr/bin/env python
"""Every pre-registered endpoint, reported (plan.md §6).

`plan.md` §6 names RMSE as primary and **Spearman, MAE, R² and precision@10%**
as secondary. The manuscript reported RMSE, Spearman and R², declared MAE and
precision@10% in §4.3, and then never mentioned them again -- though both are
computed and stored in all 1,040 runs. Selective endpoint reporting is precisely
what pre-registration exists to prevent, so this script reports all of them.

It matters here. precision@10% is the enrichment view -- the fraction of the
predicted top decile that is truly in the top decile, which is what a screening
campaign actually consumes -- and on that endpoint the transfer arms *beat* the
fingerprint baseline, reversing the sign of the primary result.

Writes results/tables/table14_all_endpoints.csv
"""
from __future__ import annotations

import glob
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

OUT = Path("results/tables/table14_all_endpoints.csv")
BASELINE = "B1_ecfp_histgb"
# (metric, lower_is_better)
ENDPOINTS = [("rmse", True), ("mae", True), ("r2", False),
             ("spearman", False), ("precision_at_10pct", False)]
ORDER = ["B0_median", "B1_ecfp_histgb", "B2_descriptors_rf",
         "T0r_untrained_encoder_probe", "T1_chemberta_linear_probe",
         "T2_chemberta_full_finetune", "T4_indomain_probe", "T5_chained_probe"]


# The family is each endpoint's own arm comparisons: 7 on RMSE, 6 elsewhere
# (B0 is a constant predictor, so Spearman is undefined for it and it is tested
# on RMSE only, as the sanity floor rather than a competitor). §5.7 reports the
# pooled 31-test correction alongside, as a sensitivity analysis rather than as
# a claim that pooling is the uniquely correct family.
def holm(p):
    p = np.asarray(p, float); order = np.argsort(p); m = len(p)
    adj = np.empty(m); run = 0.0
    for r, i in enumerate(order):
        run = max(run, min(1.0, p[i] * (m - r))); adj[i] = run
    return adj


def main() -> int:
    M = defaultdict(dict)
    for f in glob.glob("results/metrics/*__scaffold__*n347.json"):
        d = json.load(open(f))
        M[d["arm"]][d["seed"]] = d["metrics"]

    rows = []
    for metric, lower in ENDPOINTS:
        base = M[BASELINE]
        for arm in ORDER:
            if arm not in M:
                continue
            v = M[arm]
            row = {"arm": arm, "metric": metric,
                   "median": round(float(np.median([m[metric] for m in v.values()])), 4),
                   "n_seeds": len(v)}
            if arm not in (BASELINE, "B0_median") or metric == "rmse":
                s = sorted(set(v) & set(base))
                x = np.array([v[i][metric] for i in s])
                y = np.array([base[i][metric] for i in s])
                if arm != BASELINE:
                    row["median_delta_vs_B1"] = round(
                        float(np.median(y - x)) if lower else float(np.median(x - y)), 4)
                    row["arm_better_in_seeds"] = int((x < y).sum() if lower else (x > y).sum())
                    row["p_raw"] = round(float(stats.wilcoxon(x, y).pvalue), 4)
            rows.append(row)

    df = pd.DataFrame(rows)
    # Correct within each endpoint's arm family, as §5.4 does for RMSE.
    df["p_holm"] = np.nan
    for metric, _ in ENDPOINTS:
        m = (df.metric == metric) & df.p_raw.notna()
        if m.any():
            df.loc[m, "p_holm"] = holm(df.loc[m, "p_raw"]).round(4)
    df["verdict"] = np.where(
        df.p_holm.isna(), "",
        np.where(df.p_holm <= 0.05,
                 np.where(df.median_delta_vs_B1 > 0, "beats B1", "worse than B1"),
                 "inconclusive"))

    OUT.write_text(
        f"# generated by scripts/analyse_endpoints.py on "
        f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}\n"
        f"# scaffold split, full training fold; Holm-corrected within each endpoint\n"
        + df.to_csv(index=False))
    print(f"wrote {OUT}")
    piv = df.pivot_table(index="arm", columns="metric", values="median")
    print(piv.reindex(ORDER).to_string())
    print()
    print(df[(df.metric == "precision_at_10pct") & df.p_raw.notna()][
        ["arm", "median", "median_delta_vs_B1", "arm_better_in_seeds",
         "p_raw", "p_holm", "verdict"]].to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
