#!/usr/bin/env python
"""Audit every split file for leakage and report fold composition.

Produces results/tables/table0_split_audit.csv (Table 0 in the manuscript).
Reports, per split and seed: fold sizes, compounds shared between train and
test, and Bemis-Murcko scaffolds shared between train and test.
"""
from __future__ import annotations

import glob
import json
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from evapro.data.io import load_dataset

OUT = Path("results/tables/table0_split_audit.csv")


def main() -> int:
    df = load_dataset("eva71_2a")
    scaf = dict(zip(df["inchikey"], df["scaffold"]))

    rows = []
    for path in sorted(glob.glob("data/processed/splits/eva71_2a/*.json")):
        folds = json.loads(Path(path).read_text())["folds"]
        by = {}
        for key, fold in folds.items():
            by.setdefault(fold, set()).add(key)
        tr, te = by.get("train", set()), by.get("test", set())
        strategy, seed = Path(path).stem.split("__")
        rows.append({
            "split": strategy, "seed": int(seed.replace("seed", "")),
            "n_train": len(tr), "n_val": len(by.get("val", set())), "n_test": len(te),
            "compounds_in_train_and_test": len(tr & te),
            "scaffolds_in_train_and_test": len({scaf[k] for k in tr} & {scaf[k] for k in te}),
            "n_test_scaffolds": len({scaf[k] for k in te}),
        })

    out = pd.DataFrame(rows).sort_values(["split", "seed"])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as fh:
        fh.write(f"# generated by scripts/audit_splits.py on "
                 f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}\n")
        fh.write("# inputs: data/processed/splits/eva71_2a/*.json, data/processed/eva71_2a.csv\n")
        out.to_csv(fh, index=False)

    print(out.groupby("split")[["n_train", "n_test", "compounds_in_train_and_test",
                                "scaffolds_in_train_and_test"]].agg(["min", "max"]).to_string())
    print(f"\nwrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
