#!/usr/bin/env python
"""Aggregate results/metrics/*.json into the tables and figures used in the paper.

Every artefact this writes carries a provenance header naming this script and the
inputs it read, so no number in the manuscript is untraceable.

Usage: python scripts/make_report.py
Outputs:
  results/tables/table1_learning_curves__<split>.csv
  results/tables/table2_der__<split>.csv
  results/tables/table3_paired_tests__<split>.csv
  results/figures/fig1_learning_curves__<split>.png
"""
from __future__ import annotations

import argparse
import glob
import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

from evapro.evaluation.stats import data_efficiency_ratio, n_to_reach, paired_compare

METRICS = Path("results/metrics")
TABLES = Path("results/tables")
FIGURES = Path("results/figures")
BASELINE = "B1_ecfp_histgb"

# The Holm family for the headline paired tests is the arm list frozen in
# plan.md §4, and only that. Arms added later (the untrained-encoder control and
# the in-domain arms of §6.4) are NOT folded in: doing so would retroactively
# change the correction applied to the pre-registered comparisons every time a
# new arm is run, which is precisely the researcher degree of freedom the
# pre-registration exists to remove. Those arms are compared in
# analyse_indomain.py as pre-specified pairwise contrasts instead.
PREREGISTERED_FAMILY = {
    "B0_median", "B1_ecfp_histgb", "B2_descriptors_rf",
    "T1_chemberta_linear_probe", "T2_chemberta_full_finetune",
}
PRIMARY_METRIC = "rmse"

# Validated categorical palette (dataviz skill, light mode; see docs/figures.md).
# Contrast WARN on slots 3-5 -> relief shipped as direct labels + distinct markers.
PALETTE = {
    "B0_median":                 ("#8a8a85", "o", "B0 median"),
    "B1_ecfp_histgb":            ("#2a78d6", "s", "B1 ECFP4+HistGB"),
    "B2_descriptors_rf":         ("#eb6834", "^", "B2 descriptors+RF"),
    "T1_chemberta_linear_probe": ("#1baf7a", "D", "T1 ChemBERTa probe"),
    "T2_chemberta_full_finetune":("#eda100", "v", "T2 ChemBERTa FT"),
    # In-domain arms. Seven series exceeds what the categorical palette is
    # validated for, so figures that include these are drawn as focused
    # comparisons (B1 vs T1 vs T4 vs T5) rather than all-arm panels.
    "T0r_untrained_encoder_probe":("#b0b0aa", "*", "T0r untrained encoder"),
    "T4_indomain_probe":         ("#7c5cd6", "P", "T4 in-domain probe"),
    "T5_chained_probe":          ("#c8407a", "X", "T5 chained probe"),
    "T4c_indomain_probe_decontaminated": ("#9d86e0", "P", "T4 in-domain (decontam.)"),
    "T5c_chained_probe_decontaminated":  ("#d9769c", "X", "T5 chained (decontam.)"),
}
ORDER = list(PALETTE)


def provenance(inputs: str) -> str:
    return (f"# generated by scripts/make_report.py on "
            f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}\n"
            f"# inputs: {inputs}\n")


def load() -> pd.DataFrame:
    rows = []
    for f in sorted(glob.glob(str(METRICS / "*.json"))):
        r = json.load(open(f))
        rows.append({"arm": r["arm"], "split": r["split"], "seed": r["seed"],
                     "n_train": r["n_train"], **r["metrics"]})
    if not rows:
        raise SystemExit("no metrics in results/metrics -- run scripts/run_arms.py first.")
    return pd.DataFrame(rows)


def write_csv(df: pd.DataFrame, path: Path, inputs: str, index=True) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as fh:
        fh.write(provenance(inputs))
        df.to_csv(fh, index=index)
    print(f"  wrote {path}")


def _median_ci(values, n_resamples=10000, seed=0, alpha=0.05):
    """Percentile bootstrap CI for the median, resampling over SEEDS.

    The unit of replication is the seed (each seed is an independent split +
    model fit), so the bootstrap resamples seeds -- not test-set rows, which
    would understate split variance.
    """
    v = np.asarray(values, dtype=float)
    if len(v) < 2:
        return float("nan"), float("nan")
    rng = np.random.default_rng(seed)
    draws = np.median(rng.choice(v, size=(n_resamples, len(v)), replace=True), axis=1)
    lo, hi = np.percentile(draws, [100 * alpha / 2, 100 * (1 - alpha / 2)])
    return float(lo), float(hi)


def table_learning_curves(df, split) -> pd.DataFrame:
    g = (df[df.split == split]
         .groupby(["arm", "n_train"])[PRIMARY_METRIC]
         .agg(median="median", iqr=lambda s: s.quantile(.75) - s.quantile(.25),
              std="std", n_seeds="count"))
    sp = (df[df.split == split].groupby(["arm", "n_train"])["spearman"]
          .median().rename("spearman_median"))
    r2 = (df[df.split == split].groupby(["arm", "n_train"])["r2"]
          .median().rename("r2_median"))

    ci = (df[df.split == split].groupby(["arm", "n_train"])[PRIMARY_METRIC]
          .apply(lambda s: pd.Series(_median_ci(s), index=["ci_lo", "ci_hi"]))
          .unstack())
    return g.join(sp).join(r2).join(ci).round(4)


def table_der(df, split) -> pd.DataFrame:
    curves = (df[df.split == split].groupby(["arm", "n_train"])[PRIMARY_METRIC]
              .median().reset_index().sort_values("n_train"))
    base = curves[curves.arm == BASELINE]
    if base.empty:
        return pd.DataFrame()
    full_n = base.n_train.max()
    target = float(base[base.n_train == full_n][PRIMARY_METRIC].iloc[0])
    base_curve = (base.n_train.tolist(), base[PRIMARY_METRIC].tolist())

    rows = []
    for arm, gg in curves.groupby("arm"):
        curve = (gg.n_train.tolist(), gg[PRIMARY_METRIC].tolist())
        rows.append({
            "arm": arm,
            "target_rmse": round(target, 4),
            "n_to_reach_target": n_to_reach(*curve, target=target),
            "DER_vs_" + BASELINE: (1.0 if arm == BASELINE
                                   else data_efficiency_ratio(base_curve, curve, target)),
        })
    return pd.DataFrame(rows).sort_values("arm")


def table_paired(df, split) -> pd.DataFrame:
    d = df[df.split == split]
    full_n = d.n_train.max()
    at_full = d[d.n_train == full_n]
    scores = {a: g.sort_values("seed")[PRIMARY_METRIC].tolist()
              for a, g in at_full.groupby("arm") if a in PREREGISTERED_FAMILY}
    scores = {a: v for a, v in scores.items() if len(v) == len(scores.get(BASELINE, []))}
    if BASELINE not in scores or len(scores) < 2:
        return pd.DataFrame()
    res = paired_compare(scores, baseline=BASELINE, lower_is_better=True)
    return pd.DataFrame([{
        "arm": c.arm, "baseline": c.baseline, "n_train": int(full_n),
        "median_rmse_delta_vs_baseline": round(c.median_delta, 4),
        "p_raw": round(c.p_raw, 5), "p_holm": round(c.p_holm, 5),
        "n_seeds": c.n_seeds,
        "verdict": "inconclusive" if c.inconclusive else "significant",
    } for c in res])


def table_split_difficulty(df) -> pd.DataFrame:
    """Table 4: cross-split comparison at full training data.

    Raw RMSE is NOT comparable across splits, because the splits produce test
    folds with different pActivity variance (a stricter split concentrates
    chemically similar, similarly-active compounds). Reported here are the
    variance-normalised R2 and skill relative to the median predictor on the
    same split, both of which are comparable.
    """
    full_n = df.n_train.max()
    d = df[df.n_train == full_n]

    b0 = (d[d.arm == "B0_median"].groupby(["split", "seed"])[PRIMARY_METRIC]
          .median().rename("b0_rmse"))
    m = d[d.arm != "B0_median"].merge(b0, on=["split", "seed"], how="left")
    m["skill_vs_b0"] = 1.0 - m[PRIMARY_METRIC] / m["b0_rmse"]

    out = (m.groupby(["arm", "split"])
             .agg(rmse_median=(PRIMARY_METRIC, "median"),
                  r2_median=("r2", "median"),
                  spearman_median=("spearman", "median"),
                  skill_vs_b0_median=("skill_vs_b0", "median"),
                  n_seeds=("seed", "count"))
             .round(4).reset_index())
    return out.sort_values(["arm", "split"])


def figure_learning_curves(df, split) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    d = df[df.split == split]
    fig, ax = plt.subplots(figsize=(7.2, 4.6), dpi=200)
    fig.patch.set_facecolor("#fcfcfb"); ax.set_facecolor("#fcfcfb")

    # Collect end-points first so direct labels can be de-collided.
    ends = []
    for arm in ORDER:
        if arm not in set(d.arm):
            continue
        color, marker, label = PALETTE[arm]
        g = d[d.arm == arm].groupby("n_train")[PRIMARY_METRIC]
        med, lo, hi = g.median(), g.quantile(.25), g.quantile(.75)
        ax.fill_between(med.index, lo, hi, color=color, alpha=0.13, linewidth=0)
        ax.plot(med.index, med.values, color=color, marker=marker, markersize=6,
                linewidth=2, label=label, markeredgecolor="#fcfcfb", markeredgewidth=1.2)
        ends.append([med.values[-1], med.index[-1], label, color])

    # Push apart direct labels that would overlap (the relief the contrast
    # WARN requires is useless if the labels are unreadable).
    ends.sort()
    lo_ax, hi_ax = ax.get_ylim()
    min_gap = (hi_ax - lo_ax) * 0.045
    for i in range(1, len(ends)):
        if ends[i][0] - ends[i - 1][0] < min_gap:
            ends[i][0] = ends[i - 1][0] + min_gap
    for y_text, x, label, color in ends:
        ax.annotate(label, (x, y_text), textcoords="offset points", xytext=(9, 0),
                    va="center", fontsize=8, color="#52514e")

    ax.set_xscale("log")
    ax.set_xticks(sorted(d.n_train.unique()))
    ax.get_xaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())
    # Suppress log minor ticks -- they collide with the explicit size ticks.
    ax.get_xaxis().set_minor_formatter(matplotlib.ticker.NullFormatter())
    ax.get_xaxis().set_minor_locator(matplotlib.ticker.NullLocator())
    ax.set_xlabel("training set size (compounds, log scale)", fontsize=9, color="#52514e")
    ax.set_ylabel("test RMSE (pK$_D$)  ↓ better", fontsize=9, color="#52514e")
    ax.set_title(f"Learning curves, {split} split — EV-A71/CVA16 2A protease",
                 fontsize=10.5, color="#0b0b0b", loc="left")
    ax.grid(axis="y", color="#e5e5e2", linewidth=0.8)
    ax.set_axisbelow(True)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    for s in ("left", "bottom"):
        ax.spines[s].set_color("#c9c9c4")
    ax.tick_params(colors="#52514e", labelsize=8)
    ax.legend(frameon=False, fontsize=8, loc="lower left", ncol=2)
    ax.margins(x=0.22, y=0.10)
    fig.tight_layout()

    FIGURES.mkdir(parents=True, exist_ok=True)
    out = FIGURES / f"fig1_learning_curves__{split}.png"
    fig.savefig(out, facecolor=fig.get_facecolor())
    plt.close(fig)
    print(f"  wrote {out}")


def figure_ranking_curves(df, split) -> None:
    """Figure 2: Spearman rho. Bounded [0,1], so it is not compressed by the
    fine-tune arm's low-n RMSE excursion, and it is the view that separates
    ranking ability from calibration (see manuscript 5.6)."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    d = df[(df.split == split) & (df.arm != "B0_median")]
    if d.empty:
        return
    fig, ax = plt.subplots(figsize=(7.2, 4.6), dpi=200)
    fig.patch.set_facecolor("#fcfcfb"); ax.set_facecolor("#fcfcfb")

    ends = []
    for arm in ORDER:
        if arm not in set(d.arm):
            continue
        color, marker, label = PALETTE[arm]
        g = d[d.arm == arm].groupby("n_train")["spearman"]
        med, lo, hi = g.median(), g.quantile(.25), g.quantile(.75)
        ax.fill_between(med.index, lo, hi, color=color, alpha=0.13, linewidth=0)
        ax.plot(med.index, med.values, color=color, marker=marker, markersize=6,
                linewidth=2, label=label, markeredgecolor="#fcfcfb", markeredgewidth=1.2)
        ends.append([med.values[-1], med.index[-1], label])

    ends.sort()
    lo_ax, hi_ax = ax.get_ylim()
    min_gap = (hi_ax - lo_ax) * 0.045
    for i in range(1, len(ends)):
        if ends[i][0] - ends[i - 1][0] < min_gap:
            ends[i][0] = ends[i - 1][0] + min_gap
    for y_text, x, label in ends:
        ax.annotate(label, (x, y_text), textcoords="offset points", xytext=(9, 0),
                    va="center", fontsize=8, color="#52514e")

    ax.set_xscale("log")
    ax.set_xticks(sorted(d.n_train.unique()))
    ax.get_xaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())
    ax.get_xaxis().set_minor_formatter(matplotlib.ticker.NullFormatter())
    ax.get_xaxis().set_minor_locator(matplotlib.ticker.NullLocator())
    ax.set_xlabel("training set size (compounds, log scale)", fontsize=9, color="#52514e")
    ax.set_ylabel(r"test Spearman $\rho$   ↑ better", fontsize=9, color="#52514e")
    ax.set_title(f"Ranking ability, {split} split — EV-A71/CVA16 2A protease",
                 fontsize=10.5, color="#0b0b0b", loc="left")
    ax.grid(axis="y", color="#e5e5e2", linewidth=0.8)
    ax.set_axisbelow(True)
    for sp in ("top", "right"):
        ax.spines[sp].set_visible(False)
    for sp in ("left", "bottom"):
        ax.spines[sp].set_color("#c9c9c4")
    ax.tick_params(colors="#52514e", labelsize=8)
    ax.legend(frameon=False, fontsize=8, loc="lower right", ncol=2)
    ax.margins(x=0.22, y=0.12)
    fig.tight_layout()
    out = FIGURES / f"fig2_ranking__{split}.png"
    fig.savefig(out, facecolor=fig.get_facecolor())
    plt.close(fig)
    print(f"  wrote {out}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--exclude-arms", nargs="*", default=[],
                    help="arm ids to leave out (e.g. an arm whose sweep is incomplete)")
    ap.add_argument("--require-seeds", type=int, default=None,
                    help="drop any (arm, split, n) cell with fewer than this many seeds")
    args = ap.parse_args()

    df = load()
    if args.exclude_arms:
        df = df[~df.arm.isin(args.exclude_arms)]
        print(f"excluded arms: {args.exclude_arms}")
    if args.require_seeds:
        counts = df.groupby(["arm", "split", "n_train"])["seed"].transform("count")
        dropped = sorted(df[counts < args.require_seeds].arm.unique())
        df = df[counts >= args.require_seeds]
        if dropped:
            print(f"dropped cells with <{args.require_seeds} seeds from: {dropped}")
    inputs = f"results/metrics/*.json ({len(df)} records)"
    print(f"loaded {len(df)} metric records; arms={sorted(df.arm.unique())}")

    for split in sorted(df.split.unique()):
        write_csv(table_learning_curves(df, split),
                  TABLES / f"table1_learning_curves__{split}.csv", inputs)
        der = table_der(df, split)
        if not der.empty:
            write_csv(der, TABLES / f"table2_der__{split}.csv", inputs, index=False)
        paired = table_paired(df, split)
        if not paired.empty:
            write_csv(paired, TABLES / f"table3_paired_tests__{split}.csv", inputs, index=False)
        figure_learning_curves(df, split)
        figure_ranking_curves(df, split)

    if df.split.nunique() > 1:
        write_csv(table_split_difficulty(df),
                  TABLES / "table4_split_difficulty.csv", inputs, index=False)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
