#!/usr/bin/env python
"""Measure pretraining-corpus contamination for the ChemBERTa-2 arms (plan.md §7.1).

The exact ChemBERTa-2 pretraining set (77M PubChem compounds) is not
redistributed, so it cannot be diffed directly. What IS checkable is membership
in PubChem itself, which is a strict superset of that corpus. Therefore:

  - a compound ABSENT from PubChem cannot have been in the pretraining corpus
  - a compound PRESENT in PubChem may or may not have been

This yields a genuine UPPER BOUND on exact-match contamination, which is the
direction that matters here: transfer arms lose, so contamination could only
have flattered them. A low upper bound strengthens the negative result.

Writes results/tables/table5_contamination.csv.
Usage: python scripts/measure_contamination.py [--limit N]
"""
from __future__ import annotations

import argparse
import json
import time
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
import requests

from evapro.data.io import load_dataset
from evapro.data.splits import load_split

PUBCHEM = "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/inchikey/{}/cids/JSON"
OUT = Path("results/tables/table5_contamination.csv")
CACHE = Path("data/interim/pubchem_lookup.json")
SPLIT_DIR = Path("data/processed/splits/eva71_2a")
RATE_LIMIT_S = 0.22   # PubChem allows ~5 requests/second


def lookup(inchikeys: list[str]) -> dict[str, bool]:
    cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    todo = [k for k in inchikeys if k not in cache]
    print(f"{len(cache)} cached, {len(todo)} to query")

    for i, key in enumerate(todo, 1):
        try:
            r = requests.get(PUBCHEM.format(key), timeout=30)
            if r.status_code == 200:
                cache[key] = bool(r.json().get("IdentifierList", {}).get("CID"))
            elif r.status_code == 404:
                cache[key] = False
            else:
                cache[key] = None          # unknown; excluded from denominators
        except requests.RequestException:
            cache[key] = None
        if i % 50 == 0:
            print(f"  {i}/{len(todo)}", flush=True)
            CACHE.parent.mkdir(parents=True, exist_ok=True)
            CACHE.write_text(json.dumps(cache, sort_keys=True))
        time.sleep(RATE_LIMIT_S)

    CACHE.parent.mkdir(parents=True, exist_ok=True)
    CACHE.write_text(json.dumps(cache, sort_keys=True))
    return cache


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=None)
    args = ap.parse_args()

    df = load_dataset("eva71_2a")
    keys = df["inchikey"].tolist()[: args.limit]
    found = lookup(keys)

    df = df[df["inchikey"].isin(found)].copy()
    df["in_pubchem"] = df["inchikey"].map(found)
    known = df[df["in_pubchem"].notna()]

    rows = [{
        "scope": "all curated compounds",
        "split": "-", "seed": "-",
        "n": len(known),
        "n_in_pubchem": int(known["in_pubchem"].sum()),
        "frac_in_pubchem": round(float(known["in_pubchem"].mean()), 4),
    }]

    for split in ("scaffold", "random", "butina"):
        fracs, ns, hits = [], [], []
        for seed in range(10):
            path = SPLIT_DIR / f"{split}__seed{seed}.json"
            if not path.exists():
                continue
            folds = load_split(path)
            test = known[known["inchikey"].map(folds) == "test"]
            if len(test):
                fracs.append(float(test["in_pubchem"].mean()))
                ns.append(len(test)); hits.append(int(test["in_pubchem"].sum()))
        if fracs:
            rows.append({
                "scope": "test fold (median over seeds)",
                "split": split, "seed": "0-9",
                "n": int(pd.Series(ns).median()),
                "n_in_pubchem": int(pd.Series(hits).median()),
                "frac_in_pubchem": round(float(pd.Series(fracs).median()), 4),
            })

    out = pd.DataFrame(rows)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as fh:
        fh.write(f"# generated by scripts/measure_contamination.py on "
                 f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}\n")
        fh.write("# PubChem membership is an UPPER BOUND on ChemBERTa-2 pretraining overlap:\n")
        fh.write("# PubChem is a superset of the 77M pretraining corpus, so absence proves\n")
        fh.write("# non-membership while presence does not prove membership.\n")
        fh.write(f"# unresolved lookups excluded: {int(df['in_pubchem'].isna().sum())}\n")
        out.to_csv(fh, index=False)
    print(out.to_string(index=False))
    print(f"\nwrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
