#!/usr/bin/env python
"""Independently verify the CVA16/EV-A71 2A protease surrogate claim (§3.1).

§3.1 rests on a statement from Lithgo et al. (2024): the 2A protease sequences
of EV-A71 and CVA16 differ by five amino acids, none near or predicted to
affect the active site. It conditions the entire study -- every "EV-A71" result
here is strictly a CVA16 result -- and during the 2026-09-02 citation audit the
quoted sentence could not be re-retrieved (bioRxiv rate-limited it and there is
no PMC mirror).

Rather than keep trying to confirm that a paper says something, this script
checks the underlying fact from primary sequence data: it pulls the annotated
Protease 2A chains from UniProt and compares them residue by residue. That is
a stronger check than the citation it replaces, and it is re-runnable.

Writes results/tables/table9_surrogate_divergence.csv
Usage: python scripts/verify_surrogate.py [--refresh]
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
import requests

CACHE = Path("data/interim/uniprot_2a.json")
OUT = Path("results/tables/table9_surrogate_divergence.csv")

REFERENCE = ("Q66478", "EV-A71 BrCr/1970")
SURROGATES = [("Q65900", "CVA16 G-10"), ("Q9QF31", "CVA16 Tainan/5079/98")]
CHAIN_NAMES = {"Protease 2A", "Picornain 2A"}


def fetch(acc: str) -> dict:
    cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    if acc not in cache:
        r = requests.get(f"https://rest.uniprot.org/uniprotkb/{acc}.json", timeout=60)
        r.raise_for_status()
        cache[acc] = r.json()
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        CACHE.write_text(json.dumps(cache, sort_keys=True))
    return cache[acc]


def chain_2a(acc: str) -> tuple[str, int, dict]:
    """Return the annotated 2A sequence, its polyprotein offset, and site
    annotations renumbered to 1..len(2A)."""
    d = fetch(acc)
    seq = d["sequence"]["value"]
    span = next((f["location"] for f in d["features"]
                 if f["type"] == "Chain"
                 and f.get("description", "").strip() in CHAIN_NAMES), None)
    if span is None:
        raise SystemExit(f"{acc}: no annotated 2A chain")
    s, e = span["start"]["value"], span["end"]["value"]
    sites = {"catalytic": [], "zinc": []}
    for f in d["features"]:
        loc = f["location"]
        if "start" not in loc or loc["start"].get("value") is None:
            continue
        pos = loc["start"]["value"]
        if not (s <= pos <= e):
            continue
        if f["type"] == "Active site":
            sites["catalytic"].append(pos - s + 1)
        elif f["type"] == "Binding site" and "Zn" in f.get("ligand", {}).get("name", ""):
            sites["zinc"].append(pos - s + 1)
    return seq[s - 1:e], s, sites


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--refresh", action="store_true", help="ignore the cache")
    args = ap.parse_args()
    if args.refresh and CACHE.exists():
        CACHE.unlink()

    ref_seq, _, ref_sites = chain_2a(REFERENCE[0])
    cat, zinc = sorted(ref_sites["catalytic"]), sorted(ref_sites["zinc"])

    rows = []
    for acc, label in SURROGATES:
        seq, _, _ = chain_2a(acc)
        if len(seq) != len(ref_seq):
            raise SystemExit(f"{acc}: 2A length {len(seq)} != reference {len(ref_seq)}; "
                             "an alignment would be required and this script assumes none")
        diffs = [(i + 1, a, b) for i, (a, b) in enumerate(zip(ref_seq, seq)) if a != b]
        pos = [p for p, _, _ in diffs]
        rows.append({
            "reference": REFERENCE[1], "surrogate": label, "uniprot": acc,
            "chain_length": len(seq),
            "n_differences": len(diffs),
            "differences": " ".join(f"{a}{p}{b}" for p, a, b in diffs),
            "catalytic_positions": " ".join(map(str, cat)),
            "n_differences_at_catalytic_site": len(set(pos) & set(cat)),
            "min_separation_from_catalytic": min(abs(p - c) for p in pos for c in cat),
            "zinc_positions": " ".join(map(str, zinc)),
            "n_differences_at_zinc_site": len(set(pos) & set(zinc)),
            "min_separation_from_zinc": min(abs(p - z) for p in pos for z in zinc),
        })

    df = pd.DataFrame(rows)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        f"# generated by scripts/verify_surrogate.py on "
        f"{datetime.now(timezone.utc).isoformat(timespec='seconds')}\n"
        f"# source: UniProt annotated 'Protease 2A' chains; reference {REFERENCE[0]}\n"
        + df.to_csv(index=False))
    print(f"wrote {OUT}")
    print(df.drop(columns=["differences"]).to_string(index=False))
    for r in rows:
        print(f"\n{r['surrogate']}: {r['n_differences']} differences -> {r['differences']}")
    print(f"\ncatalytic triad (2A numbering): {cat}   structural Zn ligands: {zinc}")
    print("no differing position is catalytic in either surrogate: "
          f"{all(r['n_differences_at_catalytic_site'] == 0 for r in rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
